blank_issues_enabled: false
contact_links:
  - name: Comunidade
    url: https://github.com/isaacplay/isaacplay/discussions
    about: Por favor, pergunte e responda perguntas aqui.
  - name: Documentação
    url: https://github.com/isaacplay/isaacplay/wiki
    about: Por favor, leia a documentação antes de abrir uma issue. 