name: Auto Close

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    if: github.event.issue.labels.*.name == 'wontfix' || github.event.pull_request.labels.*.name == 'wontfix'
    steps:
      - name: Auto Close
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue || context.payload.pull_request;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: 'This issue has been automatically closed because it was labeled as "wontfix". If you believe this was done in error, please remove the label and provide additional context.'
            });
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              state: 'closed'
            }); 