name: Auto Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Backup database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/isaacplay
            timestamp=$(date +%Y%m%d_%H%M%S)
            docker-compose exec -T db pg_dump -U postgres > backup_$timestamp.sql
            gzip backup_$timestamp.sql
            mv backup_$timestamp.sql.gz /backup/

      - name: Upload backup to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync backup to S3
        run: |
          aws s3 sync /backup s3://${{ secrets.AWS_BACKUP_BUCKET }}/backups

      - name: Cleanup old backups
        run: |
          # Keep only the last 30 days of backups
          find /backup -type f -mtime +30 -delete 