name: Auto Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for updates
        id: check
        run: |
          npm outdated || true
          if [ $? -eq 0 ]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Update dependencies
        if: steps.check.outputs.updates_available == 'true'
        run: |
          npm update
          npm audit fix

      - name: Create Pull Request
        if: steps.check.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies'
          body: |
            This PR updates the project dependencies to their latest versions.
            
            Changes made:
            - Updated npm packages to their latest versions
            - Applied security fixes from npm audit
            
            Please review the changes and merge if everything looks good.
          branch: update-dependencies
          base: main
          labels: |
            dependencies
            automated pr 